/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wizardsc
 */
public class HoaDonGUI extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonGUI
     */
    public HoaDonGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbpPhieuNhap = new javax.swing.JTabbedPane();
        pnPhieuNhap = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        btnXoa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbxDonViTinh = new javax.swing.JComboBox<>();
        btnNhapLai = new javax.swing.JLabel();
        btnThemVaoGio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        btnThongTinSP = new javax.swing.JButton();
        pnChiTietPhieuNhap = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSCTHD = new javax.swing.JTable();
        txtDonGiainDSCTHD = new javax.swing.JTextField();
        txtSoLuonginDSCTHD = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtMaSPinDSCTHD = new javax.swing.JTextField();
        txtTenSPinDSCTHD = new javax.swing.JTextField();
        txtThanhTieninDSCTHD = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        btnResetSearchDSCTHD = new javax.swing.JLabel();
        txtTuKhoainDSCTHD = new javax.swing.JTextField();
        rdbMaSPinDSCTHD = new javax.swing.JRadioButton();
        rdbTenSPinDSCTHD = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        txtDonGiaBDinDSCTHD = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDonGiaKTinDSCTHD = new javax.swing.JTextField();
        txtSoLuongKTinDSCTHD = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSoLuongBDinDSCTHD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnTimKiemDSCTHD = new javax.swing.JLabel();
        rdbThongThuonginDSCTHD = new javax.swing.JRadioButton();
        rdbDonGiaNCinDSCTHD = new javax.swing.JRadioButton();
        rdbSoLuongNCinDSCTHD = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDSHD = new javax.swing.JTable();
        txtMaHDinDSHD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtMaKHinDSHD = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMaNVinDSHD = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtNgayLapinDSHD = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTongTieninDSHD = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        rdbMaHD = new javax.swing.JRadioButton();
        txtTuKhoaDSHD = new javax.swing.JTextField();
        rdbMaNV = new javax.swing.JRadioButton();
        rdbMaKH = new javax.swing.JRadioButton();
        btnResetSearchDSHD = new javax.swing.JLabel();
        txtTongTienB = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtTongTienA = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnTimKiemHD = new javax.swing.JLabel();
        rdbThongThuong = new javax.swing.JRadioButton();
        rdbTongTienNC = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(250, 247, 240));

        tbpPhieuNhap.setBackground(new java.awt.Color(250, 247, 240));
        tbpPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbpPhieuNhap.setFont(new java.awt.Font("Baloo 2 ExtraBold", 0, 13)); // NOI18N
        tbpPhieuNhap.setInheritsPopupMenu(true);

        pnPhieuNhap.setBackground(new java.awt.Color(250, 247, 240));
        pnPhieuNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(250, 247, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GIỎ HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baloo 2 ExtraBold", 0, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblGioHang);

        btnXoa.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(btnXoa))
        );

        pnPhieuNhap.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 570, 430));

        jPanel5.setBackground(new java.awt.Color(250, 247, 240));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN SẢN PHẨM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baloo 2 ExtraBold", 0, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Mã SP");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tên SP");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Đơn giá");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Đơn vị tính");

        cbxDonViTinh.setEditable(true);
        cbxDonViTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn đơn vị tính", "Cái", "Lon", "Hộp", "Gói", "Thùng", "Tuýp", "Miếng", "Hũ", "Chai", "Cây" }));

        btnNhapLai.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapLaiMouseClicked(evt);
            }
        });

        btnThemVaoGio.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btnThemVaoGio.setText("Thêm vào giỏ");
        btnThemVaoGio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemVaoGio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemVaoGioMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Thành tiền");

        btnThongTinSP.setText("...");
        btnThongTinSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txtTenSP)
                            .addComponent(txtSoLuong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemVaoGio)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxDonViTinh, 0, 142, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNhapLai)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtDonGia))))
                .addGap(61, 61, 61))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel10)
                        .addComponent(cbxDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemVaoGio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnPhieuNhap.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 569, 230));

        tbpPhieuNhap.addTab("Hóa đơn", pnPhieuNhap);

        pnChiTietPhieuNhap.setBackground(new java.awt.Color(233, 213, 218));

        jPanel6.setBackground(new java.awt.Color(233, 213, 218));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT HÓA ĐƠN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baloo 2 ExtraBold", 0, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        tblDSCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSCTHD.getTableHeader().setReorderingAllowed(false);
        tblDSCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDSCTHD);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Số lượng");

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Đơn giá");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Thành tiền");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Tên SP");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Mã SP");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Nhập từ khóa");

        btnResetSearchDSCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetSearchDSCTHDMouseClicked(evt);
            }
        });

        rdbMaSPinDSCTHD.setBackground(new java.awt.Color(233, 213, 218));
        rdbMaSPinDSCTHD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbMaSPinDSCTHD.setText("Mã SP");

        rdbTenSPinDSCTHD.setBackground(new java.awt.Color(233, 213, 218));
        rdbTenSPinDSCTHD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbTenSPinDSCTHD.setText("Tên SP");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Tìm kiếm thành tiền từ:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("đến:");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("đến:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Tìm kiếm số lượng từ:");

        btnTimKiemDSCTHD.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btnTimKiemDSCTHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTimKiemDSCTHD.setText("Tìm kiếm");
        btnTimKiemDSCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemDSCTHDMouseClicked(evt);
            }
        });

        rdbThongThuonginDSCTHD.setBackground(new java.awt.Color(233, 213, 218));

        rdbDonGiaNCinDSCTHD.setBackground(new java.awt.Color(233, 213, 218));

        rdbSoLuongNCinDSCTHD.setBackground(new java.awt.Color(233, 213, 218));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenSPinDSCTHD)
                                    .addComponent(txtMaSPinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSoLuonginDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDonGiainDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtThanhTieninDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(rdbDonGiaNCinDSCTHD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDonGiaKTinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbThongThuonginDSCTHD)
                                    .addComponent(rdbSoLuongNCinDSCTHD))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTuKhoainDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnResetSearchDSCTHD)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbMaSPinDSCTHD)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbTenSPinDSCTHD))
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(txtSoLuongBDinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel19))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(txtDonGiaBDinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17)))
                                        .addGap(36, 36, 36)
                                        .addComponent(txtSoLuongKTinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnTimKiemDSCTHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMaSPinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(txtDonGiainDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txtTenSPinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuonginDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtThanhTieninDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbMaSPinDSCTHD)
                        .addComponent(rdbTenSPinDSCTHD))
                    .addComponent(btnResetSearchDSCTHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rdbThongThuonginDSCTHD)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTuKhoainDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDonGiaKTinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDonGiaBDinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(rdbDonGiaNCinDSCTHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuongBDinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtSoLuongKTinDSCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiemDSCTHD))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rdbSoLuongNCinDSCTHD)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel7.setBackground(new java.awt.Color(233, 213, 218));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH HÓA ĐƠN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baloo 2 ExtraBold", 0, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        tblDSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Mã KH", "Mã NV", "Ngày tạo", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSHD.getTableHeader().setReorderingAllowed(false);
        tblDSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDSHD);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Mã HD");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Mã KH");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Mã NV");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setText("Ngày lập");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Tổng tiền");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Nhập từ khóa");

        rdbMaHD.setBackground(new java.awt.Color(233, 213, 218));
        rdbMaHD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbMaHD.setText("Mã HĐ");

        rdbMaNV.setBackground(new java.awt.Color(233, 213, 218));
        rdbMaNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbMaNV.setText("Mã NV");

        rdbMaKH.setBackground(new java.awt.Color(233, 213, 218));
        rdbMaKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdbMaKH.setText("Mã KH");

        btnResetSearchDSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetSearchDSHDMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("đến:");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Tìm kiếm tổng tiền từ:");

        btnTimKiemHD.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btnTimKiemHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTimKiemHD.setText("Tìm kiếm");
        btnTimKiemHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiemHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemHDMouseClicked(evt);
            }
        });

        rdbThongThuong.setBackground(new java.awt.Color(233, 213, 218));

        rdbTongTienNC.setBackground(new java.awt.Color(233, 213, 218));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaKHinDSHD, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(txtMaHDinDSHD))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtMaNVinDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNgayLapinDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtTongTieninDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbThongThuong, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdbTongTienNC, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTongTienA, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtTongTienB))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTuKhoaDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnResetSearchDSHD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdbMaHD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdbMaKH)
                                        .addGap(6, 6, 6)
                                        .addComponent(rdbMaNV)))))))
                .addContainerGap())
            .addComponent(btnTimKiemHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaHDinDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtMaNVinDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtMaKHinDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayLapinDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtTongTieninDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResetSearchDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(txtTuKhoaDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdbMaHD)
                                .addComponent(rdbMaNV)
                                .addComponent(rdbMaKH))
                            .addComponent(rdbThongThuong))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtTongTienA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txtTongTienB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rdbTongTienNC))
                .addGap(18, 18, 18)
                .addComponent(btnTimKiemHD)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnChiTietPhieuNhapLayout = new javax.swing.GroupLayout(pnChiTietPhieuNhap);
        pnChiTietPhieuNhap.setLayout(pnChiTietPhieuNhapLayout);
        pnChiTietPhieuNhapLayout.setHorizontalGroup(
            pnChiTietPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietPhieuNhapLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnChiTietPhieuNhapLayout.setVerticalGroup(
            pnChiTietPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChiTietPhieuNhapLayout.createSequentialGroup()
                .addGroup(pnChiTietPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        tbpPhieuNhap.addTab("Chi tiết hóa đơn", pnChiTietPhieuNhap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPhieuNhap)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1082, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemHDMouseClicked
//        ImageIcon icon = new ImageIcon(getClass().getResource("/image/warning.png"));
//        if (rdbThongThuong.isSelected()) {
//            if (txtTuKhoaDSHD.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE, icon);
//            }
//            if (rdbMaHD.isSelected()) {
//                dshd = hdBUS.timKiemTheoMaHD(txtTuKhoaDSHD.getText().toString());
//                showAllDSHD(dshd);
//            }
//            if (rdbMaNV.isSelected()) {
//                dshd = hdBUS.timKiemTheoMaNV(txtTuKhoaDSHD.getText().toString());
//                showAllDSHD(dshd);
//            }
//            if (rdbMaKH.isSelected()) {
//                dshd = hdBUS.timKiemTheoMaKH(txtTuKhoaDSHD.getText().toString());
//                showAllDSHD(dshd);
//            }
//
//        }
//        if (rdbTongTienNC.isSelected()) {
//            buttonGroup1.clearSelection();
//            if (txtTongTienA.getText().equals("") || txtTongTienB.getText().equals("")) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập dữ liệu cần tìm kiếm", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE, icon);
//            } else {
//                int x = Integer.parseInt(txtTongTienA.getText());
//                int y = Integer.parseInt(txtTongTienB.getText());
//                dshd = hdBUS.timKiemTongTienNangCao(x, y);
//                showAllDSHD(dshd);
//            }
//        }
    }//GEN-LAST:event_btnTimKiemHDMouseClicked

    private void btnResetSearchDSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetSearchDSHDMouseClicked
//        buttonGroup1.clearSelection();
//        buttonGroup2.clearSelection();
//        txtTuKhoaDSHD.setText("");
//        txtTongTienA.setText("");
//        txtTongTienB.setText("");
//        loadDataDSHD();
    }//GEN-LAST:event_btnResetSearchDSHDMouseClicked

    private void tblDSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSHDMouseClicked
        int k = tblDSHD.getSelectedRow();
        txtMaHDinDSHD.setEnabled(false);
        txtMaKHinDSHD.setEnabled(false);
        txtMaNVinDSHD.setEnabled(false);
        txtNgayLapinDSHD.setEnabled(false);
        txtTongTieninDSHD.setEnabled(false);
        txtMaHDinDSHD.setText(tblDSHD.getModel().getValueAt(k, 0).toString());
        txtMaKHinDSHD.setText(tblDSHD.getModel().getValueAt(k, 1).toString());
        txtMaNVinDSHD.setText(tblDSHD.getModel().getValueAt(k, 2).toString());
        txtNgayLapinDSHD.setText(tblDSHD.getModel().getValueAt(k, 3).toString());
        txtTongTieninDSHD.setText(tblDSHD.getModel().getValueAt(k, 4).toString());
        String MaHD = txtMaHDinDSHD.getText();

//        loadDataDSCTHDTheoMaHD(MaHD);
    }//GEN-LAST:event_tblDSHDMouseClicked

    private void btnTimKiemDSCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemDSCTHDMouseClicked
        if (rdbThongThuonginDSCTHD.isSelected()) {
            if (txtTuKhoainDSCTHD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin cần tìm", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                if (rdbMaSPinDSCTHD.isSelected()) {
//                    ArrayList<ChiTietHDDTO> dscthd = cthdBUS.timKiemMaSP(txtTuKhoainDSCTHD.getText());
//                    showAllDSCTHD(dscthd);
                }
                if (rdbTenSPinDSCTHD.isSelected()) {
//                    ArrayList<ChiTietHDDTO> dscthd = cthdBUS.timKiemTenSP(txtTuKhoainDSCTHD.getText());
//                    showAllDSCTHD(dscthd);
                }
            }
        }

        if (rdbDonGiaNCinDSCTHD.isSelected()) {
            if (txtDonGiaBDinDSCTHD.getText().equals("") || txtDonGiaKTinDSCTHD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin cần tìm", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
//                ArrayList<ChiTietHDDTO> dscthd = cthdBUS.timKiemThanhTienNangCao(Integer.parseInt(txtDonGiaBDinDSCTHD.getText()), Integer.parseInt(txtDonGiaKTinDSCTHD.getText()));
//                showAllDSCTHD(dscthd);
            }
        }
        if (rdbSoLuongNCinDSCTHD.isSelected()) {
            if (txtSoLuongBDinDSCTHD.getText().equals("") || txtSoLuongKTinDSCTHD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin cần tìm", "Thông báo", JOptionPane.WARNING_MESSAGE);

            } else {
//                ArrayList<ChiTietHDDTO> dscthd = cthdBUS.timKiemSoLuongNangCao(Integer.parseInt(txtSoLuongBDinDSCTHD.getText()), Integer.parseInt(txtSoLuongKTinDSCTHD.getText()));
//                showAllDSCTHD(dscthd);
            }
        }
    }//GEN-LAST:event_btnTimKiemDSCTHDMouseClicked

    private void btnResetSearchDSCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetSearchDSCTHDMouseClicked
        txtTuKhoainDSCTHD.setText("");
        txtDonGiaBDinDSCTHD.setText("");
        txtDonGiaKTinDSCTHD.setText("");
        txtSoLuongBDinDSCTHD.setText("");
        txtSoLuongKTinDSCTHD.setText("");
//        buttonGroup3.clearSelection();
//        buttonGroup4.clearSelection();
//        loadDataDSCTHD();
    }//GEN-LAST:event_btnResetSearchDSCTHDMouseClicked

    private void tblDSCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSCTHDMouseClicked
        int k = tblDSCTHD.getSelectedRow();
        txtMaSPinDSCTHD.setText(tblDSCTHD.getModel().getValueAt(k, 0).toString());
        txtTenSPinDSCTHD.setText(tblDSCTHD.getModel().getValueAt(k, 1).toString());
        txtSoLuonginDSCTHD.setText(tblDSCTHD.getModel().getValueAt(k, 2).toString());
        txtDonGiainDSCTHD.setText(tblDSCTHD.getModel().getValueAt(k, 3).toString());
        txtThanhTieninDSCTHD.setText(tblDSCTHD.getModel().getValueAt(k, 4).toString());

        txtMaSPinDSCTHD.setEnabled(false);
        txtTenSPinDSCTHD.setEnabled(false);
        txtSoLuonginDSCTHD.setEnabled(false);
        txtDonGiainDSCTHD.setEnabled(false);
        txtThanhTieninDSCTHD.setEnabled(false);
    }//GEN-LAST:event_tblDSCTHDMouseClicked

    private void btnThongTinSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinSPActionPerformed
        //        RecentWareHouseGUI wh = new RecentWareHouseGUI();
        //        wh.setVisible(true);
//        RecentWareHouseGUI.setUndecorated(true);
//        RecentWareHouseGUI.pack();
//        RecentWareHouseGUI.setLocationRelativeTo(null);
//        RecentWareHouseGUI.setVisible(true);
//
//        String MaSP = getMaSPWH();
//        String TenSP = getTenSPWH();
//        String DonViTinh = getDonViTinhWH();
//        String DonGia = getDonGiaWH();
//        String SoLuong = getSoLuongWH();
//        int ThanhTien = Integer.parseInt(DonGia) * Integer.parseInt(SoLuong);
//        String SoLuongTrongKho = getSoLuongTrongKhoWH();

//        txtMaSP.setText(MaSP);
//        txtTenSP.setText(TenSP);
//        cbxDonViTinh.setSelectedItem(DonViTinh);
//        txtDonGia.setText(DonGia);
//        txtSoLuong.setText(SoLuong);
//        txtThanhTien.setText(String.valueOf(ThanhTien));

        txtMaSP.setEnabled(false);
        cbxDonViTinh.setEnabled(false);
        txtTenSP.setEnabled(false);
        txtDonGia.setEnabled(false);
        txtSoLuong.setEnabled(false);
        txtThanhTien.setEnabled(false);
    }//GEN-LAST:event_btnThongTinSPActionPerformed

    private void btnThemVaoGioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemVaoGioMouseClicked
//        if(txtMaHD.getText().equals("")){
//            JOptionPane.showMessageDialog(btnThemVaoGio, "Vui lòng nhập mã hóa đơn", "THÔNG BÁO",JOptionPane.ERROR_MESSAGE);
//        } else {
//            String MaHD = txtMaHD.getText();
//            String MaSP = txtMaSP.getText();
//            String TenSP = txtTenSP.getText();
//            int SoLuong = Integer.parseInt(txtSoLuong.getText());
//            int DonGia = Integer.parseInt(txtDonGia.getText());
//            int k = tblDSSP.getSelectedRow();
//            int SoLuongConLai = Integer.parseInt(tblDSSP.getModel().getValueAt(k,4).toString());
//            spBUS.capNhatSoLuongHD(MaSP, -SoLuong, SoLuongConLai);
//            spBUS.docDanhSach();
//            boolean flag = true;
//            for(ChiTietHDDTO cthd : dscthd){
//                if(cthd.getMaSP().equals(MaSP)){
//                    int old = cthd.getSoLuong();
//                    cthd.setSoLuong(old+SoLuong);
//                    int new1 = cthd.getSoLuong();
//                    cthd.setThanhTien(new1*DonGia);
//                    flag = false;
//                    break;
//                }
//            }
//            if(flag){
//                dscthd.add(new ChiTietHDDTO(MaHD, MaSP, TenSP, SoLuong, DonGia, DonGia));
//
//            }
//            outModel(dtmGioHang, dscthd);
//            txtTongTien.setText(String.valueOf(sumHD()));
//            loadDataWareHouse();
//            txtMaSP.setText("");
//            txtTenSP.setText("");
//            txtSoLuong.setText("");
//            txtDonGia.setText("");
//            txtThanhTien.setText("");
//            cbxDonViTinh.setSelectedIndex(0);
//        }
    }//GEN-LAST:event_btnThemVaoGioMouseClicked

    private void btnNhapLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapLaiMouseClicked
        txtMaSP.setEnabled(true);
        cbxDonViTinh.setEnabled(true);
        txtTenSP.setEnabled(true);
        txtDonGia.setEnabled(true);
        txtSoLuong.setEnabled(true);
        txtThanhTien.setEnabled(true);

        txtMaSP.setText("");
        cbxDonViTinh.setSelectedIndex(0);
        txtTenSP.setText("");
        txtDonGia.setText("");
        txtSoLuong.setText("");
        txtThanhTien.setText("");
    }//GEN-LAST:event_btnNhapLaiMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        int k = tblGioHang.getSelectedRow();
//        dscthd.remove(k);
//        dtmGioHang.removeRow(k);
//        txtTongTien.setText(String.valueOf(sumHD()));
//        loadDataWareHouse();
        btnNhapLaiMouseClicked(evt);
    }//GEN-LAST:event_btnXoaMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        int k = tblGioHang.getSelectedRow();

        txtMaSP.setText(tblGioHang.getModel().getValueAt(k, 0).toString());
        txtSoLuong.setText(tblGioHang.getModel().getValueAt(k, 2).toString());
    }//GEN-LAST:event_tblGioHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnNhapLai;
    private javax.swing.JLabel btnResetSearchDSCTHD;
    private javax.swing.JLabel btnResetSearchDSHD;
    private javax.swing.JLabel btnThemVaoGio;
    private javax.swing.JButton btnThongTinSP;
    private javax.swing.JLabel btnTimKiemDSCTHD;
    private javax.swing.JLabel btnTimKiemHD;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JComboBox<String> cbxDonViTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnChiTietPhieuNhap;
    private javax.swing.JPanel pnPhieuNhap;
    private javax.swing.JRadioButton rdbDonGiaNCinDSCTHD;
    private javax.swing.JRadioButton rdbMaHD;
    private javax.swing.JRadioButton rdbMaKH;
    private javax.swing.JRadioButton rdbMaNV;
    private javax.swing.JRadioButton rdbMaSPinDSCTHD;
    private javax.swing.JRadioButton rdbSoLuongNCinDSCTHD;
    private javax.swing.JRadioButton rdbTenSPinDSCTHD;
    private javax.swing.JRadioButton rdbThongThuong;
    private javax.swing.JRadioButton rdbThongThuonginDSCTHD;
    private javax.swing.JRadioButton rdbTongTienNC;
    private javax.swing.JTable tblDSCTHD;
    private javax.swing.JTable tblDSHD;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTabbedPane tbpPhieuNhap;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonGiaBDinDSCTHD;
    private javax.swing.JTextField txtDonGiaKTinDSCTHD;
    private javax.swing.JTextField txtDonGiainDSCTHD;
    private javax.swing.JTextField txtMaHDinDSHD;
    private javax.swing.JTextField txtMaKHinDSHD;
    private javax.swing.JTextField txtMaNVinDSHD;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMaSPinDSCTHD;
    private javax.swing.JTextField txtNgayLapinDSHD;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongBDinDSCTHD;
    private javax.swing.JTextField txtSoLuongKTinDSCTHD;
    private javax.swing.JTextField txtSoLuonginDSCTHD;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenSPinDSCTHD;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtThanhTieninDSCTHD;
    private javax.swing.JTextField txtTongTienA;
    private javax.swing.JTextField txtTongTienB;
    private javax.swing.JTextField txtTongTieninDSHD;
    private javax.swing.JTextField txtTuKhoaDSHD;
    private javax.swing.JTextField txtTuKhoainDSCTHD;
    // End of variables declaration//GEN-END:variables
}
